procedures:
  - name: fato.prQDataCicloDetalhado
    output_folder: ciclo_detalhado
    params:
      - name: DataInicial
        type: datetime
        position: 1
      - name: DataFinal
        type: datetime
        position: 2
  - name: fato.prQDataCicloDetalhadoLatLon
    output_folder: ciclo_detalhado_latlon
    params:
      - name: dataInicial
        type: datetime
        position: 1
      - name: dataFinal
        type: datetime
        position: 2
  - name: fato.prQDataApropriacoes
    output_folder: apropriacoes
    params:
      - name: DT1
        type: datetime
        position: 1
      - name: DT2
        type: datetime
        position: 2
      - name: TPR
        type: varchar
        position: 3
      - name: CLASSIFICACAO
        type: nvarchar
        position: 4
        default: '-1'
      - name: SETORID
        type: nvarchar
        position: 5
        default: '-1'
      - name: USUARIOID
        type: int
        position: 6
        default: 2115
      - name: proprietarioID
        type: nvarchar
        position: 7
        default: '-1'
      - name: turnoID
        type: nvarchar
        position: 8
        default: '-1'
      - name: turmaID
        type: nvarchar
        position: 9
        default: '-1'
      - name: operadorID
        type: nvarchar
        position: 10
        default: '-1'
      - name: frotaTransporteID
        type: nvarchar
        position: 11
        default: '-1'
      - name: equipamentoID
        type: nvarchar
        position: 12
        default: '-1'