procedures:
  - name: fato.prQDataCicloDetalhado
    output_folder: ciclo_detalhado
    table: fato.CicloDetalhado
    date_column: datahorainicio
    params:
      - name: DataInicial
        type: datetime
        position: 1
      - name: DataFinal
        type: datetime
        position: 2
  - name: fato.prQDataCicloDetalhadoLatLon
    output_folder: ciclo_detalhado_latlon
    table: fato.CicloDetalhadoLatLon
    date_column: datahorainicio
    params:
      - name: dataInicial
        type: datetime
        position: 1
      - name: dataFinal
        type: datetime
        position: 2
  - name: fato.prQDataIndicesOperacionais
    output_folder: indices_operacionais
    table: fato.IndicesOperacionais
    date_column: data
    params:
      - name: dataInicial
        type: datetime
        position: 1
      - name: dataFinal
        type: datetime
        position: 2
  - name: fato.prQDataApropriacoes
    output_folder: apropriacoes
    table: fato.Apropriacoes
    date_column: datahorainicio
    params:
      - name: DT1
        type: datetime
        position: 1
      - name: DT2
        type: datetime
        position: 2